### PR TITLE
Add Apythonados - CM community

### PR DESCRIPTION
**Pull request by erneani**

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hey there, as you can see, the tests failed, since we need an URL in the file :(

Do you have anything you can put it for now, like a Telegram/Slack group, temporary page etc?

**Comment by erneani** [comment]
Oh, I will try to get the Telegram group url :D

**Comment by erneani** [comment]
Done!

**Comment by jonatasbaldin** [comment]
Thanks 🐍

**Pull request merged**
