### PR TITLE
Add Cameroon Python Academy Community

### PR DESCRIPTION
**Pull request by nejos97**
We want to share our work with other python developer around the world.

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hello there, how are you doing?

This map is for local communities only, and by the name it seems to be a course website of some sorts... is this accurate? If so, I won't be able to merge this.

Also, I couldn't access your link, I get a 404 from Bitly.

**Comment by nejos97** [comment]
In fact we have a python community but we do not have a website yet. but our community is getting better and better and we want to make it known to the world to share with them too. are there anything I need to do to have my data added to the database?

**Comment by jonatasbaldin** [comment]
Alright, thanks! The name `Python Academy` made me think it was a course website or something. 

It would be nice if you could add a valid URL, it could be a Whatsapp/Telegram group, Meetup page, Twitter account, anything that links to the group. Do you have something like that?

Cheers!

**Comment by jonatasbaldin** [comment]
Nice, thanks!

**Pull request merged**
